run_analysis <- function(data_path="UCI HAR Dataset") {
  
  # check if data folder exists or not; terminate gracefully if cannot find the data set
  if (!file.exists(data_path)) stop(paste("Cannot find the data files! Please make sure the following folder exists:", data_path) )
  
  # read feature names and activity labels
  features <-read.table( paste(data_path, "/features.txt", sep=""))
  activity <-read.table( paste(data_path, "/activity_labels.txt", sep=""))
  
  # filter columns with 'mean' or 'std' of features
  measure_col <- sort(c(grep("mean()", features[,2]),grep("std()", features[,2]))) 
  measure_name <- features[measure_col,2]

  # read and process test data to extract relevant columns; and lable the columns by feature names
  test_x <- read.table( paste(data_path, "/test/X_test.txt", sep=""), colClasses = "numeric")
  test_x <- test_x[, measure_col]
  names(test_x) <- measure_name
  test_y <- read.table( paste(data_path, "/test/y_test.txt", sep=""), colClasses = "numeric")
  test_y <- lapply( test_y, function(elt) elt<-activity[elt,2])
  subject_test <- read.table( paste(data_path, "/test/subject_test.txt", sep=""), colClasses = "numeric")
  
  # read and process train data to extract relevant columns; and lable the columns by feature names
  train_x <- read.table( paste(data_path, "/train/X_train.txt", sep=""), colClasses = "numeric")
  train_x <- train_x[, measure_col]
  names(train_x) <- measure_name
  train_y <- read.table( paste(data_path, "/train/y_train.txt", sep=""), colClasses = "numeric")
  train_y <- lapply( train_y, function(elt) elt<-activity[elt,2])
  subject_train <- read.table( paste(data_path, "/train/subject_train.txt", sep=""), colClasses = "numeric")
  
  # merge the data and labels the activity and subject columns and assign the data set to 'measurement_data'
  measurement_data <- rbind( cbind(test_y, subject_test, test_x), cbind(train_y, subject_train, train_x) ) 
  names(measurement_data)[1:2] <- c("Activity", "Subject")
  
  # calculate the average of each variable for each activity and each subjecxt; sorting the output 
  measurement_average <- aggregate(measurement_data[,3:ncol(measurement_data)], by=list(measurement_data[,1], measurement_data[,2]), "mean")
  names(measurement_average)[1:2] <- c("Activity", "Subject")
  measurement_average<-measurement_average[order(measurement_average$Activity,measurement_average$Subject),]
  
  # remove the row name generated by the sorting 
  rownames(measurement_average) <- NULL
  
  # write the tidy.txt 
  write.table(measurement_average, "tidy.txt", row.names = FALSE)
  
  # return the tidy data set
  return(measurement_average)
}